image: atlassian/default-image:2

pipelines:
  branches:
    master:
    - step:
       name: supply server pipeline
       deployment: common-services-fe Sdeployment
       script:
         - pipe: atlassian/ssh-run:0.2.2
           variables:
             SSH_USER: $USER
             SERVER: $SUPPLY_SERVER
             COMMAND: 'cd /home/team21/deploy && ./common-services-fe-deploy.sh'
    - step:
        name: demand server pipeline
        deployment: common-services-fe Ddeployment
        script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: $USER
              SERVER: $DEMAND_SERVER
              COMMAND: 'cd /home/team21/deploy && ./common-services-fe-deploy.sh'